@host = localhost:7294
@app_origin = https://localhost:7209

GET https://{{host}}/api/store/products
Accept: application/json
Origin: {{app_origin}}

###

GET https://{{host}}/api/store/product/6819944fb45e03d3e67e926f
Accept: application/json
Origin: {{app_origin}}

###

POST https://{{host}}/api/store/product
Accept: application/json
Content-Type: application/json
Origin: {{app_origin}}

{
    "category_id": "000000000000000000000000",
    "name": "Corpse Flower",
    "store_location": "Roleystone",
    "post_code": "6111",
    "price": 10,
    "is_available": true
}

###

PUT https://{{host}}/api/store/product/6819e7fa2e12ae3d1e9f1c7f
Accept: application/json
Content-Type: application/json
Origin: {{app_origin}}

{
    "category_id": "000000000000000000000000",
    "name": "Daisy",
    "store_location": "Roleystone",
    "post_code": "6111",
    "price": 10,
    "is_available": true
}

###

DELETE https://{{host}}/api/store/product/000000000000000000000000
Accept: application/json
Origin: {{app_origin}}

###

GET https://{{host}}/api/store/categories
Accept: application/json
Origin: {{app_origin}}

###
